#!/bin/bash

eww="eww -c $HOME/.config/eww/bar/"

toggle() {
    wpctl set-mute @DEFAULT_SINK@ toggle
}

get_volume() {
    value=$(wpctl get-volume @DEFAULT_SINK@ | grep -Eo '(0.[0-9]{2})|(1.00)' | sed -E '{ 's/0\.00/0/'; ; t; { s/(0\.0*)//; t; s/(1\.)/1/; }; }' -)
    echo "${value}"
}

volume() {
    if [[ $1 == "down" ]]; then
	wpctl set-volume -l 1 @DEFAULT_SINK@ $2%+
    elif [[ $1 == "up" ]]; then
	wpctl set-volume -l 1 @DEFAULT_SINK@ $2%-
    else
	value=$(get_volume)
	wpctl set-volume @DEFAULT_SINK@ "${value}%"
    fi
    get_volume
}

icon() {
    mute=$(wpctl get-volume @DEFAULT_SINK@ | grep -Eo 'MUTE')
    icon=""
    if [[ ${mute} == "MUTE" ]]; then
	icon=""
	${eww} update volume-color='#f26435'
	${eww} update volume-value="${icon}"
	exit 1
    else
	if (( 70 < $1 && $1 <= 100 )); then
	    icon=""
	elif (( 30 < $1 && $1 <= 70 )); then
	    icon=""
	elif (( 0 <= $1 && $1 <= 30 )); then
	    icon=""
	fi
    fi
    echo $icon
}

value=""

if [[ $1 == "toggle" ]]; then
    toggle
fi

value=$(volume $1 $2)
icon=$(icon $value)

if [[ -z ${icon} ]]; then exit 0; fi

${eww} update volume-color=''
${eww} update volume-value="${icon}  ${value}%"
