#!/bin/bash

eww="eww -c $HOME/.config/eww/bar/"

value=$(printf "%.0f\n" $(free -m | grep Mem | awk '{print ($3/$2)*100}'))
class=""

if (( ${value} >= 90 )); then
    class="button-critical"
elif (( ${value} >= 60 )); then
    class="button-warning"
fi

${eww} update memory-animation=${class}
echo ${value}
